

const DATABASE_HOST = 'localhost'
const DATABASE_PORT = 3306
const DATABASE_USERNAME = 'root'
const DATABASE_PASSWORD = 'qhl4233..'
const DATABASE_NAME = 'osp'

const APP_PORT = 3000


export {
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_USERNAME,
    DATABASE_PASSWORD,
    DATABASE_NAME,
    APP_PORT
}
